[project]
name = "play-music"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.2",
    "pydub>=0.25.1",
    "pygame>=2.6.1",
]
